version: 0.2

phases:
  install:
    runtime-version:
      nodejs:12
  pre_build:
    commands:
      - echo install first server
      - cd server
      - npm install
      - cd ..
      - cd client
      - npm install
      - cd ..

  build:
    commands:
      - echo Running test
      - cd server
      - npm test
      - cd ..
      - cd client
      - npm test