apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 5001
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
spec:
    replicas: 1  
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                -   name: server
                    image: atillataha/server:v2
                    ports:
                        - containerPort: 5001